In [2]:
import pandas as pd
import pickle

In [50]:
eth_ds = pd.read_csv("../data/processed/eth_dataset_complete.csv")

In [51]:
eth_ds

,Unnamed: 0,ethereum_address,ether_balance,unique_tokens,unique_transfers,mined_blocks
0,0,0x8d12a197cb00d4747a1fe03395095ce2a5cc6819,17960.597685,9900,117342,0
1,1,0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208,19345.149872,1718,54180,0
2,2,0x0d0707963952f2fba59dd06f2b425ace40b492fe,443.735122,587,245377,0
3,3,0xab5c66752a9e8167967685f1450532fb96d5d24f,331.840176,402,443233,0
4,4,0x1ce7ae555139c5ef5a57cc8d814a867ee6ee33d8,747.701162,978,18360,0
...,...,...,...,...,...,...
26524,26524,0x4d5a77b869312a8e2b3daa67c01c59753f6254ae,281.630258,47,12,0
26525,26525,0xd2ad5f590192d227cb7e6ff15743119fe26118a0,1000.954777,47,4,0
26526,26526,0x603f39c81560019c8360f33ba45bc1e4caecb33e,176.012588,47,7,0
26527,26527,0x003e93083a2d294cb8c4421048108330c37b5874,669.846139,47,2,0
26528,26528,0x72ac49403ae54061fbcdaaae032607c3f1e2f567,976.648574,47,2,0

In [55]:
eth_ds.drop(["Unnamed: 0"], axis=1, inplace=True)

In [57]:
eth_ds[205:215]

,ethereum_address,ether_balance,unique_tokens,unique_transfers,mined_blocks
205,0xbff3f531e6301d84a884be362aef4b0394e79388,1400.050790,48,2,0
206,0xb9c764114c5619a95d7f232594e3b8dddf95b9cf,2162.328018,59,11793,0
207,0xe8e8f41ed29e46f34e206d7d2a7d6f735a3ff2cb,40515.987064,106,19,0
208,0x2905a0393342f45df5763835e9d4aaf2b4c87d79,20299.296693,76,2,0
209,0x88884e35d7006ae84efef09ee6bc6a43dd8e2bb8,1462.051423,111,16,0
210,0x926fc576b7facf6ae2d08ee2d4734c134a743988,245.980362,51,3,0
211,0x6cf0569bf06069e27fca1ff3d6cb398116f0a097,3138.311690,148,15,0
212,0x792d8cde8624fd02185328b426a0b9e9b8a1a25f,663.800327,131,21,1167990
213,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,2767.258964,168,35,0
214,0x655996746cba6e46f9fbe91a34df3cf3c2be9823,272.608285,71,8,0

In [56]:
eth_ds

,ethereum_address,ether_balance,unique_tokens,unique_transfers,mined_blocks
0,0x8d12a197cb00d4747a1fe03395095ce2a5cc6819,17960.597685,9900,117342,0
1,0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208,19345.149872,1718,54180,0
2,0x0d0707963952f2fba59dd06f2b425ace40b492fe,443.735122,587,245377,0
3,0xab5c66752a9e8167967685f1450532fb96d5d24f,331.840176,402,443233,0
4,0x1ce7ae555139c5ef5a57cc8d814a867ee6ee33d8,747.701162,978,18360,0
...,...,...,...,...,...
26524,0x4d5a77b869312a8e2b3daa67c01c59753f6254ae,281.630258,47,12,0
26525,0xd2ad5f590192d227cb7e6ff15743119fe26118a0,1000.954777,47,4,0
26526,0x603f39c81560019c8360f33ba45bc1e4caecb33e,176.012588,47,7,0
26527,0x003e93083a2d294cb8c4421048108330c37b5874,669.846139,47,2,0
26528,0x72ac49403ae54061fbcdaaae032607c3f1e2f567,976.648574,47,2,0

In [58]:
for i, row in eth_ds.iterrows():
    mined = row.mined_blocks
    try:
        eth_ds.iat[i+1, 4] = mined
    except IndexError:
        continue

In [59]:
eth_ds[205:215]

,ethereum_address,ether_balance,unique_tokens,unique_transfers,mined_blocks
205,0xbff3f531e6301d84a884be362aef4b0394e79388,1400.050790,48,2,0
206,0xb9c764114c5619a95d7f232594e3b8dddf95b9cf,2162.328018,59,11793,0
207,0xe8e8f41ed29e46f34e206d7d2a7d6f735a3ff2cb,40515.987064,106,19,0
208,0x2905a0393342f45df5763835e9d4aaf2b4c87d79,20299.296693,76,2,0
209,0x88884e35d7006ae84efef09ee6bc6a43dd8e2bb8,1462.051423,111,16,0
210,0x926fc576b7facf6ae2d08ee2d4734c134a743988,245.980362,51,3,0
211,0x6cf0569bf06069e27fca1ff3d6cb398116f0a097,3138.311690,148,15,0
212,0x792d8cde8624fd02185328b426a0b9e9b8a1a25f,663.800327,131,21,0
213,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,2767.258964,168,35,1167990
214,0x655996746cba6e46f9fbe91a34df3cf3c2be9823,272.608285,71,8,0

In [62]:
eth_ds.to_csv("../data/processed/eth_dataset.csv", index=False)

In [11]:
price_ds = pickle.load(open("../../data/external/dflabel.p", "rb"))

In [12]:
price_ds

,label,category,address,outgoing_txns,incoming_txns,total_eth_sent,avg_eth_sent,total_usd_sent,avg_usd_sent,total_eth_recd,...,monthly_usd_recd,contracts_created,contract_txns_sent,incoming_avg_time_btwn_txns,incoming_std_time_btwn_txns,outgoing_avg_time_btwn_txns,outgoing_std_time_btwn_txns,num_tokens_used,eth_balance,cluster
0,Bgogo_1,Exchange,0x7a10ec7d68a048bdae36a70e93532d31423170fa,4634,42,55512.9469664,11.979487908,1.193449e+07,2.575420e+03,58124.066213484,...,4.162975e+06,0,0,1.383690e+05,1.409740e+05,1.257425e+03,4.127817e+03,5,486.335359084,5
1,Bgogo_2,Exchange,0xce1bf8e51f8b39e51c6184e059786d1c0eaf360f,36,5043,57900,1608.333333333,1.248853e+07,3.469036e+05,61671.7841197,...,4.418291e+06,0,0,9.234072e+02,1.880744e+04,1.373183e+05,1.435795e+05,16,4361.036312862,11
2,Rate3_Wallet2,ICO Wallets,0x841991ffe0dafd619bc517d82ee4700c37136140,7,5,5040,720,1.877741e+06,2.682487e+05,9684.7308,...,8.097912e+05,0,0,1.017963e+06,1.390813e+06,7.171660e+05,1.001970e+06,3,4644.727651874,7
3,Bitmax_1,Exchange,0x03bdf69b1322d623836afbd27679a1c0afa067e9,1061,1081,3348.282084541,3.155779533,7.798949e+05,7.350565e+02,6077.344511858,...,2.748006e+05,0,0,9.625878e+03,6.593208e+04,9.759738e+03,5.313994e+04,13,3871.119196898,11
4,Bitmax_2,Exchange,0x4b1a99467a284cc690e3237bc69105956816f762,3,1303,260,86.666666667,5.097040e+04,1.699013e+04,2958.985716476,...,1.608649e+05,0,0,8.146992e+03,1.386719e+05,1.307516e+06,1.848834e+06,3,2698.982399248,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Yunbi_1,Exchange,0xd94c9ff168dc6aebf9b6cc86deff54f3fb0afc33,260313,683,10430444.938743971,40.068859176,1.250518e+09,4.803902e+03,10541659.105013208,...,3.688945e+07,11,179574,1.197353e+05,6.832754e+05,3.264493e+02,6.107626e+03,93,871.344522953,14
122,Bittrex_1,Exchange,0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98,5488707,235407,25691539.593409785,4.680799976,9.921043e+09,1.807537e+03,3010143.011600555,...,5.078835e+05,13,1326134,4.341582e+02,2.684584e+04,1.872970e+01,4.067285e+02,503,977374.381627778,13
123,F2Pool_2,Mining,0x829bd824b016326a401d083b33d092293333a830,5984353,4050,1875938.077130069,0.313473834,9.406350e+08,1.571824e+02,6612.898084378,...,1.293509e+05,43,639507,1.017663e+04,1.277072e+05,7.319252e+00,7.005829e+02,81,8173.811332223,14
124,Yunbi_2,Exchange,0x42da8a05cb7ed9a43572b5ba1b8f82a0a6e263dc,378,11,10997397.6949,29093.644695503,1.259512e+09,3.332041e+06,18413.314948173,...,5.455062e+04,105582,143586,6.104203e+06,9.894380e+06,2.165822e+05,1.157030e+06,41,447.974371944,4
125,F2Pool_1,Mining,0x61c808d82a3ac53231750dadc13c777b59310bd9,412515,152,1578059.442718261,3.825459541,1.490286e+08,3.612683e+02,188939.386957762,...,2.893608e+06,180,581218,5.286432e+05,1.125617e+06,1.980667e+02,1.595622e+04,52,887.356769122,14

In [12]:
price_ds.rename({"address": "ethereum_address"}, axis=1, inplace=True)

In [15]:
eth_with_price = pd.merge(price_ds, eth_ds, how="inner", on="ethereum_address")

In [16]:
eth_with_price

,ethereum_address,outgoing_txns,incoming_txns,total_eth_sent,avg_eth_sent,total_usd_sent,avg_usd_sent,total_eth_recd,avg_eth_recd,total_usd_recd,...,outgoing_std_time_btwn_txns,num_tokens_used,eth_balance,Unnamed: 0,ether_balance,unique_tokens,unique_transfers,mined_blocks,Entity_x,Entity_y
0,0x292f04a44506c2fd49bac032e1ca148c35a478c8,4864,22266,9333.349076619,1.918862886,3.867294e+06,795.085045,10214.959816743,0.458769416,4.309319e+06,...,6.699476e+03,15,530.017268228,1372,293.533426,53,390,0,Unknown,NaN
1,0x2ee3b41f8413649ee1be42a1f2b10f2025b8e4d0,513,221,2346.815764972,4.5746896,8.916430e+05,1738.095479,2659.54881403,12.03415753,1.113383e+06,...,2.455692e+05,5,309.432755598,10189,150.098265,8,1,0,Unknown,NaN
2,0xc1c427cd8e6b7ee3b5f30c2e1d3f3c5536ec16f5,258,19224,23803.395909423,92.261224455,5.053698e+06,19587.976826,23816.682627404,1.238903591,5.142907e+06,...,6.037891e+05,23,69.156839325,25888,1946.874049,42,2,0,Unknown,NaN
3,0x97e12bd75bdee72d4975d6df410d2d145b3d8457,53762,35219,24454.554903179,0.454866912,1.436442e+07,267.185373,26375.261358107,0.748892966,1.559929e+07,...,1.986703e+04,27,621.559078323,981,280.783883,212,938,0,Unknown,NaN
4,0x2887704430d5d4aa2226d4c72c811d89bd7ca855,3,18,0.7,0.233333333,1.975540e+02,65.851333,766.69994568,42.594441427,1.675167e+05,...,3.325327e+06,1,765.999607055,13516,957.092132,12,2,0,Unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6052,0xc49e71b3f1cf4f6bdfddb58b47b5b923bd22e12d,7926,302,75013.43551934,9.464223507,3.528501e+07,4451.805991,75265.840783316,249.224638355,3.549252e+07,...,2.220393e+04,22,132.505141344,23938,120.112972,34,2,0,Unknown,NaN
6053,0x96e9a06a22d4445a757dfe9b4ff2c77a12dd60f2,247,195,893.54985563,3.617610752,1.812921e+05,733.976180,1429.83091942,7.332466253,2.868707e+05,...,1.790938e+04,2,497.96551995,803,136.156173,71,1304,0,Unknown,NaN
6054,0xb9cf2da90bdff1bc014720cc84f5ab99d7974eba,248,19330,23632.148122061,95.290919847,5.082940e+06,20495.726382,23644.176991533,1.223185566,5.136533e+06,...,6.244605e+05,26,69.404024379,25145,1915.497330,39,2,0,Unknown,NaN
6055,0xe19ffb70e148a76d26698036a9ffd22057967d1b,251,19208,23910.138384828,95.259515477,5.023537e+06,20014.090354,23921.403780207,1.245387535,5.154090e+06,...,6.250618e+05,26,65.229056284,24993,1933.838819,39,2,0,Unknown,NaN
6056,0x34faaa028162c4d4e92db6abfa236a8e90ff2fc3,253,19284,23669.601412789,93.555736809,5.073506e+06,20053.383780,23681.567890952,1.228042309,5.152124e+06,...,6.097747e+05,22,68.830539535,25536,1928.950501,41,2,0,Unknown,NaN

In [17]:
eth_with_price.Entity_y.value_counts()

Exchange       51
Mining         10
ICO Wallets     7
Name: Entity_y, dtype: int64

In [20]:
# Sanity check: do eth_addresses labeled as "Miners" actually have mined_blocks

eth_with_price[eth_with_price["Entity_y"] == "Mining"]

,ethereum_address,outgoing_txns,incoming_txns,total_eth_sent,avg_eth_sent,total_usd_sent,avg_usd_sent,total_eth_recd,avg_eth_recd,total_usd_recd,...,outgoing_std_time_btwn_txns,num_tokens_used,eth_balance,Unnamed: 0,ether_balance,unique_tokens,unique_transfers,mined_blocks,Entity_x,Entity_y
4926,0xeea5b82b61424df8020f5fedd81767f2d0d25bfb,2839,4,3382.781790629,1.191539905,7.518001e+05,264.811593,600,150,1.726620e+05,...,15381.421070,2,775.613016287,17719,934.258001,16,2,0,Unknown,Mining
5185,0x04668ec2f57cc15c381b461b9fedab5d451c8f7f,1821,8,1317.784856895,0.723659998,2.762415e+05,151.697710,111.998,13.99975,2.358388e+04,...,15230.350982,1,143.486955719,19576,4251.593124,18,10,0,Unknown,Mining
5815,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,9785688,368,3291571.27333116,0.336365851,6.850879e+08,70.009174,516.930397742,1.404702168,1.930168e+04,...,383.733773,82,8399.08849495,213,2767.258964,168,35,0,Unknown,Mining
5837,0x829bd824b016326a401d083b33d092293333a830,5984353,4050,1875938.077130069,0.313473834,9.406350e+08,157.182413,6612.898084378,1.632814342,2.328317e+06,...,700.582907,81,8173.811332223,354,7768.269522,121,40,0,Unknown,Mining
5863,0x00192fb10df37c9fb26829eb2cc623cd1bf599e8,213100,4,15110.188501737,0.070906563,6.214369e+06,29.161751,23.966726528,5.991681632,2.175329e+04,...,1271.616659,19,120.101956544,25023,1053.013086,39,4,0,Unknown,Mining
5970,0xea674fdde714fd979de3edf0f56aa9716b898ec8,15678630,359,4634177.920104296,0.295572886,1.335740e+09,85.194923,92321.741970097,257.163626658,6.282515e+07,...,39.078584,80,834.394598387,790,1063.450229,160,80,0,Unknown,Mining
5971,0x99c85bb64564d9ef9a99621301f22c9993cb89e3,20646,7,8636.52463117,0.418314668,2.654729e+06,128.583191,30.696505,4.385215,9.709748e+03,...,9015.707835,9,58.923416244,21854,1063.295273,25,2,0,Unknown,Mining
6019,0x2a65aca4d5fc5b5c859090a6c34d164135398226,3713483,28,4397286.82471517,1.184140825,2.294501e+08,61.788370,6031.90476593,215.425170212,8.416293e+05,...,456.952387,53,389.469176235,1102,2344.313238,97,10,0,Unknown,Mining
6025,0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01,282066,29,1343834.80451828,4.764256608,9.103881e+07,322.757113,30.166603926,1.040227722,1.095171e+03,...,649.278458,26,167.152054963,25862,116.998051,42,3,0,Unknown,Mining
6049,0x63a9975ba31b0b9626b34300f7f627147df1f526,272369,56,311171.25462329,1.142462081,1.086351e+06,3.988528,15638.38646267,279.256901119,1.479468e+04,...,1533.796694,10,332.567136223,18293,332.567136,17,1,0,Unknown,Mining